<a href="https://colab.research.google.com/github/limbospoon/NNFS/blob/dev/MLBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
inputs = [1,2,3]
weights = [0.2, 0.8, -0.5]
bias = 2

output = (inputs[0] * weights[0] +
          inputs[1] * weights[1] +
          inputs[2] * weights[2]) + bias

print(output)

2.3


In [2]:
#A single nueron with 4 inputs
inputs = [1,2,3,4]
weights = [0.2, 0.8, -0.5, 0.6]
bias = 2

output = (inputs[0] * weights[0] +
          inputs[1] * weights[1] +
          inputs[2] * weights[2] +
          inputs[3] * weights[3]) + bias

print(output)

4.7


In [4]:
#A layer with 3 nuerons
inputs = [1,2,3,4]
weights = [0.2, 0.8, -0.5, 0.6]
weights2 = [0.1, 0.75, 0.5, -0.6]
weights3 = [0.3, 0.89, -0.34, 0.68]

bias = 2
bias2 = 3
bias3 = 1.5

output = [inputs[0] * weights[0] +
          inputs[1] * weights[1] +
          inputs[2] * weights[2] +
          inputs[3] * weights[3] + bias,
          
          inputs[0] * weights2[0] +
          inputs[1] * weights2[1] +
          inputs[2] * weights2[2] +
          inputs[3] * weights2[3] + bias2,
          
          inputs[0] * weights3[0] +
          inputs[1] * weights3[1] +
          inputs[2] * weights3[2] +
          inputs[3] * weights3[3] + bias3,
          ]
          
print(output)

[4.7, 3.7, 5.28]


In [5]:
#A single layer using a for loop
inputs = [1,2,3,4]
weights = [[0.2, 0.8, -0.5, 0.6],
           [0.1, 0.75, 0.5, -0.6],
           [0.3, 0.89, -0.34, 0.68]]
biases = [2,3,1.5]

layer_output = []

for n_weights, n_biases in zip(weights, biases):
  #Zero neuron output each loop
  neuron_output = 0

  for n_input, weight in zip(inputs, n_weights):
    neuron_output += n_input * weight

  neuron_output += n_biases

  layer_output.append(neuron_output)

print(layer_output)

[4.7, 3.7, 5.28]


In [6]:
#Dot product example
a = [1,2,3]
b = [4,5,6]
dot_product = a[0]*b[0] + a[1]*b[1] + a[2]*b[2]

print(dot_product)

32


In [7]:
#Dot product numpy example
import numpy as np

inputs = [1,2,3]
weights = [0.2, 0.8, -0.5]
bias = 2

output = np.dot(weights, inputs) + bias
print(output)

2.3


In [8]:
#A layer with 3 nuerons example np
import numpy as np

inputs = [1,2,3]
weights = [[0.2, 0.8, -0.5],
           [0.45, 0.87, -0.58],
           [0.67, -0.8, 0.34]]
biases = [2,3,4]

layer_output = np.dot(weights, inputs)
print(layer_output)

[0.3  0.45 0.09]


In [9]:
#Matrix maths example
import numpy as np
a = [1,2,3]
b = [3,4,5]

a = np.array([a])
b = np.array([b]).T

print(np.dot(a,b))

[[26]]


In [10]:
#Matrix maths example 3 nuerons
import numpy as np

inputs = [[1,2,3],
          [4,5,6],
          [2.3, -5.6,4]]
weights = [[0.68, 0.24, -0.4],
          [0.33,0.58,-0.12],
           [-0.78,-0.65,0.89]]
biases = [2.0,3.0,0.5]

layer_output = np.dot(inputs, np.array(weights).T) + biases

print(layer_output)

[[ 1.96   4.13   1.09 ]
 [ 3.52   6.5   -0.53 ]
 [ 0.62   0.031  5.906]]


In [12]:
#A 2 layer NN example
import numpy as np

inputs = [[1,2,3],
          [4,5,6],
          [2.3, -5.6,4]]
weights = [[0.68, 0.24, -0.4],
          [0.33,0.58,-0.12],
           [-0.78,-0.65,0.89]]
weights2 = [[0.8, 0.4, -0.45],
          [0.3,0.5,-0.1],
           [-0.7,-0.6,0.8]]
biases = [2.0,3.0,0.5]
biases2 = [5.0,6.0,7.0]

layer_output = np.dot(inputs, np.array(weights).T) + biases
layer2_output = np.dot(layer_output, np.array(weights2).T) + biases2
print(layer2_output)

[[ 7.7295  8.544   4.022 ]
 [10.6545 10.359   0.212 ]
 [ 2.8507  5.6109 11.2722]]
